# -*- coding: utf-8 -*-
"""Workout.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VOV6H7MndHogYzEsqT5PvZcRziv3N4gj
"""

import numpy as np


for num in range(2,-5,-1):
    print(num)



a = range(10)
print(a)
for w in a:
  print(w)

if 'a'=='A':
  print('incase')
else:
  print('case')

a,b = 4,2
if (0>0):
  print('True')
else:
  print('F')

for num in range(10,14):
    for i in range(2,num):
      if num&i == 1:
        print(num)
        break

x = [0,2,4,5,6,7]
sorted(x,)
sum(x)

def dis(str,num):
 multiple = str * num
 print(multiple)
 for n in multiple:
     print(n)
dis('King',56)

print(round(12.49877,4))

import numpy as np
# a = np.array([1,2,3,4,5])
# print(a.ndim)
# print(a.size)
# a = np.zeros(6)
# b = np.arange(0,10,2)
# c = a + b
# print (c[4])
 
e = np.array([1,2,3],[0,1,4])
print(e.size)

import numpy as np
 
e = np.array([[1,2,3],[0,1,4]])
print(e.size)

size_of_vec = 10000
X_list = range(size_of_vec)
Y_list = range(size_of_vec)
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)
X_list

X